### ISSUE TITLE
Spotify Free is detected as a song

### ISSUE THREAD

**Issue by DanTm99** [SimonIT/spotifylyrics#13]
Version 1.23 addresses the detection of "Spotify Premium" as a song, but "Spotify Free" is still detected as a song, leading to it being stuck saying "Loading..." even when a song begins playing. So it seems there also seems to be a problem with it not timing out.

**Comment by SimonIT** [comment]
Thank you for reporting the problem. I own Spotify Premium, so I didn't notice. I will fix that with the next commit. 

The _Loading..._ text should go away if it can't find the lyrics and _Error: Could not find lyrics._ should appear. Maybe there is another problem so the program can't continue.

**Comment by SimonIT** [comment]
I guess I found the problem you experienced.

I this code snippet I split the name of the song into the artist and title.
https://github.com/SimonIT/spotifylyrics/blob/f0ecb6703bbcdd8f9c5ec4ee9c333a51532e07b0/backend.py#L47-L58

I assume, that the window title contains minimum one _-_. This works, because that's how Spotify separates artist and title. But the title _Spotify Free_ doesn't contain a _-_, so it fails in line 53
