### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by AlviseC** [SimonIT/spotifylyrics#22]
When i try to download the exe the Smart Screen (Windows 10) say to me that this is a virus.

Can you resolve this?

**Comment by SimonIT** [comment]
It's not a real "false positive". The Smart Screen says that the exe is not signed so you shouldn't trust it.
The signing itself is not the problem and I would do it, if I can. It's an easy process described [here](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Win-Code-Signing). The problem is the certificate which I need to sign the exe. As Microsoft describes [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate), I need to buy this certificate. This wouldn't be also problem if I don't have to pay annual multiple hundreds of euros for them. I do this project in my freetime and get nothing from it. So unless I got enough patrons on patreon to get the money or other access to a certificate which I can use, you have only the option to trust my exe's or to run the python files yourself.
