### ISSUE TITLE
Trojan detection on a few virus scanners

### ISSUE THREAD

**Issue by okkuweb** [SimonIT/spotifylyrics#42]
This dissuaded me from trying this software out for now.

Have you come by these virus scanner detections concerning the latest version 1.55 windows release zip?

https://www.virustotal.com/gui/file/65d1ddf1466cb82292734fad95876754ce51086c0e5cc7fce5168b0490a6f173/detection

Windows Defender detected the zip as "Trojan:Script/Oneeva.A!ml" as well

**Comment by SimonIT** [comment]
Hmm, that's the first time I hear of these wrong detections.
Sadly, there is probably nothing I can do. I generate the exe files with [pyinstaller](https://www.pyinstaller.org/) and don't have the money to buy certificates to sign them (#22).

I have two solutions for you if you don't trust my exe files:
1. Clone the repo and run the python files itself
2. Fork the repo and let GitHub Actions build your own exe file

**Comment by vosykapavel** [comment]
Just have an idea... Maybe if you would release the EXE file instead of windows.zip it could be downloadable without problems (then user only have to click to trust "unsigned" app).

Thanks for great job! Nice app (using 1.54)

![image](https://user-images.githubusercontent.com/3764279/114694385-c4b77500-9d1a-11eb-9650-8e57b579e281.png)

**Comment by SimonIT** [comment]
That's an idea. I will try it

**Comment by vosykapavel** [comment]
Great! Just downloaded 1.55 without problem! Thanks.

![image](https://user-images.githubusercontent.com/3764279/114712732-b7a58080-9d30-11eb-99cd-6473ceefc236.png)

**Comment by SimonIT** [comment]
Nice to hear
